"use client";

import { Container, Title, Accordion, Text, Space } from "@mantine/core";
import { MarkdownRenderer } from "@/components/shared/MarkdownRenderer";

const faqContent = [
  {
    value: "vision",
    question: "What is this platform?",
    answer: `This is a data-driven dashboard and workspace for exploring and analyzing the governance processes of major blockchain ecosystems. Our mission is to bring clarity and insight to the world of decentralized improvement proposals. We provide tools to track the lifecycle of proposals, understand contributor activity, and measure the overall health and decentralization of various protocols.`,
  },
  {
    value: "problem",
    question: "What problem does this solve?",
    answer: `Decentralized governance is powerful, but it can often be slow, opaque, and difficult for newcomers to engage with. Discussions are fragmented across forums and code repositories, making it hard to track progress. This platform tackles those challenges by providing a single, aggregated view of a protocol's entire history, making the innovation process more transparent, efficient, and accessible to everyone.`,
  },
  {
    value: "metrics",
    question: "How do you measure ecosystem health?",
    answer: `We use several key metrics to provide a clear, data-driven view of an ecosystem's health. **Activity** is measured by the number of proposals and unique authors over time. The **Acceptance Rate** shows the percentage of proposals that reach a 'Final' status versus those that were eligible (i.e., not withdrawn or abandoned), which indicates the efficiency of the governance process. The **Centralization Score** measures the distribution of influence among successful authors—a lower score suggests a healthier, more decentralized and meritocratic system where a wider group of contributors can successfully land proposals.`,
  },
  {
    value: "mission",
    question: "What is the long-term vision?",
    answer: `Our long-term vision is to create an indispensable, self-sustaining piece of public good infrastructure for the entire decentralized world. We aim to be the definitive source for analytics on cross-ecosystem governance, helping protocols learn from each other and improve their processes. We plan to enhance the platform with more advanced analytics, AI-powered insights, and tools that empower communities to build better, together.`,
  },
  {
    value: "workspace",
    question: "What is the long-term vision for the interactive workspace?",
    answer: `Beyond analytics, our vision is to build a full-featured, interactive process management system for decentralized governance. This includes a streamlined interface for **creating and editing improvement proposals directly**, with a "fork-and-PR" workflow handled seamlessly in the background. We are also designing systems to integrate user feedback directly into the governance process, including concepts like **Net Promoter Scores (NPS)** and feedback scores weighted by the on-chain activity or revenue generated by protocol users. This will create a powerful feedback loop, ensuring that the proposals being developed are directly aligned with the needs of the ecosystem's most active participants.`,
  },
  {
    value: "contact",
    question: "How can I get in touch or contribute?",
    answer: `We are always looking for collaborators, feedback, and new ecosystems to support. If you are a protocol maintainer who would like to see your project integrated, or a developer who wants to contribute to this public good, please get in touch with us at our main [website](https://peeramid.xyz/contact).`,
  },
];

export default function FaqPage() {
  return (
    <Container size="md" py="xl">
      <Title order={1} ta="center" mb="xl">
        About The Platform
      </Title>

      <Text c="dimmed" ta="center" mb="xl">
        This page provides an overview of our vision, the problems we're
        solving, and how we measure success in the decentralized governance
        space.
      </Text>

      <Accordion variant="separated" defaultValue="vision">
        {faqContent.map((item) => (
          <Accordion.Item key={item.value} value={item.value}>
            <Accordion.Control>{item.question}</Accordion.Control>
            <Accordion.Panel>
              <MarkdownRenderer content={item.answer} />
            </Accordion.Panel>
          </Accordion.Item>
        ))}
      </Accordion>

      <Space h="xl" />
    </Container>
  );
}
